### ISSUE TITLE
Teuthology Failure; AttributeError: 'Filesystem' object has no attribute 'pgs_per_fs_pool'

### ISSUE THREAD

**Issue by julpark-rh** [red-hat-storage/ceph#113]
Traceback (most recent call last):
File "/home/teuthworker/src/github.com_red-hat-storage_ceph_rh-nautilus/qa/tasks/cephfs/test_config_commands.py", line 39, in test_add_data_pool_root
 p = self.fs.add_data_pool("foo")
File "/home/teuthworker/src/github.com_red-hat-storage_ceph_rh-nautilus/qa/tasks/cephfs/filesystem.py", line 644, in add_data_pool
self.mon_manager.raw_cluster_cmd('osd', 'pool', 'create', name, self.pgs_per_fs_pool.__str__())
AttributeError: 'Filesystem' object has no attribute 'pgs_per_fs_pool'
Ran 2 tests in 70.811s

http://magna002.ceph.redhat.com/hyelloji-2020-06-29_02:11:21-kcephfs-nautilus-distro-basic-multi/379168/teuthology.log

**Comment by julpark-rh** [comment]
pool-perm.yaml, config-commands.yaml have same issue
